name: Release plugin
on:
  release:
    types: [published]
jobs:
  release:
    name: New release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Clean up release tag
      run: |
        semver_string="${initial_tag_version/v/}"
        echo "setting semver string to $semver_string"
        echo "::set-env name=semver_string::$semver_string"
      env:
        initial_tag_version: ${{ github.event.release.tag_name }}
    - name: Build
      uses: php-actions/composer@v5
      with:
        command: install
        version: 1
    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      continue-on-error: true
      with:
        generate-zip: true
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: cloudflare
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{github.workspace}}/cloudflare-$semver_string.zip
        asset_name: cloudflare-$semver_string.zip
        asset_content_type: application/zip
